// Copyright (c) 2023 Huawei Device Co., Ltd.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Asynchronous `Connector` trait and `HttpConnector` implementation.

mod stream;

use core::future::Future;
use std::io::{Error, ErrorKind};
use std::net::SocketAddr;
use std::str::FromStr;
use std::sync::Arc;

#[cfg(all(target_os = "linux", feature = "libc"))]
use libc::{gid_t, uid_t};
use ylong_http::request::uri::Uri;
#[cfg(feature = "http3")]
use ylong_runtime::net::{ConnectedUdpSocket, UdpSocket};

use crate::async_impl::dns::{DefaultDnsResolver, EyeBallConfig, HappyEyeballs, Resolver};
use crate::runtime::{AsyncRead, AsyncWrite, TcpStream};
use crate::util::config::{ConnectorConfig, HttpVersion};
/// Information of an IO.
use crate::util::ConnInfo;
use crate::{HttpClientError, Timeout};

/// `Connector` trait used by `async_impl::Client`. `Connector` provides
/// asynchronous connection establishment interfaces.
pub trait Connector {
    /// Streams that this connector produces.
    type Stream: AsyncRead + AsyncWrite + ConnInfo + Unpin + Sync + Send + 'static;

    /// Futures generated by this connector when attempting to create a stream.
    type Future: Future<Output = Result<Self::Stream, HttpClientError>>
        + Unpin
        + Sync
        + Send
        + 'static;

    /// Attempts to establish a connection.
    fn connect(&self, uri: &Uri, http_version: HttpVersion) -> Self::Future;
}

/// Connector for creating HTTP or HTTPS connections asynchronously.
///
/// `HttpConnector` implements `async_impl::Connector` trait.
pub struct HttpConnector {
    config: ConnectorConfig,
    resolver: Arc<dyn Resolver>,
}

impl HttpConnector {
    /// Creates a new `HttpConnector` with a `ConnectorConfig`.
    pub(crate) fn new(config: ConnectorConfig, resolver: Arc<dyn Resolver>) -> Self {
        Self { config, resolver }
    }

    /// Creates a new `HttpConnector` with a given dns `Resolver`.
    pub(crate) fn with_dns_resolver<R>(resolver: R) -> Self
    where
        R: Resolver,
    {
        let resolver = Arc::new(resolver) as Arc<dyn Resolver>;
        Self {
            config: Default::default(),
            resolver,
        }
    }
}

impl Default for HttpConnector {
    fn default() -> Self {
        Self {
            config: Default::default(),
            resolver: Arc::new(DefaultDnsResolver::default()),
        }
    }
}

async fn tcp_stream(eyeballs: HappyEyeballs) -> Result<TcpStream, HttpClientError> {
    eyeballs
        .connect()
        .await
        .map_err(|e| {
            #[cfg(target_os = "linux")]
            if format!("{}", e).contains("failed to lookup address information") {
                return HttpClientError::from_dns_error(crate::ErrorKind::Connect, e);
            }
            #[cfg(target_os = "windows")]
            if let Some(code) = e.raw_os_error() {
                if (0x2329..=0x26B2).contains(&code) || code == 0x2AF9 {
                    return HttpClientError::from_dns_error(crate::ErrorKind::Connect, e);
                }
            }
            HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
        })
        .and_then(|stream| match stream.set_nodelay(true) {
            Ok(()) => Ok(stream),
            Err(e) => err_from_io!(Connect, e),
        })
}

#[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
async fn tcp_stream_with_owner(
    eyeballs: HappyEyeballs,
    uid: uid_t,
    gid: gid_t,
) -> Result<TcpStream, HttpClientError> {
    eyeballs
        .connect_with_owner(uid, gid)
        .await
        .map_err(|e| {
            if format!("{}", e).contains("failed to lookup address information") {
                return HttpClientError::from_dns_error(crate::ErrorKind::Connect, e);
            }
            HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
        })
        .and_then(|stream| match stream.set_nodelay(true) {
            Ok(()) => Ok(stream),
            Err(e) => err_from_io!(Connect, e),
        })
}

async fn dns_query(
    resolver: Arc<dyn Resolver>,
    addr: &str,
) -> Result<Vec<SocketAddr>, HttpClientError> {
    if let Ok(socket_addr) = SocketAddr::from_str(addr) {
        return Ok(vec![socket_addr]);
    }
    let addr_fut = resolver.resolve(addr);
    let socket_addr = addr_fut.await.map_err(|e| {
        HttpClientError::from_dns_error(
            crate::ErrorKind::Connect,
            Error::new(ErrorKind::Interrupted, e),
        )
    })?;
    Ok(socket_addr.collect::<Vec<_>>())
}

async fn eyeballs_connect(
    addrs: Vec<SocketAddr>,
    timeout: Timeout,
) -> Result<TcpStream, HttpClientError> {
    let eyeball_config = EyeBallConfig::new(timeout.inner(), None);
    let happy_eyeballs = HappyEyeballs::new(addrs, eyeball_config);
    tcp_stream(happy_eyeballs).await
}

#[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
async fn eyeballs_connect_with_owner(
    addrs: Vec<SocketAddr>,
    timeout: Timeout,
    uid: uid_t,
    gid: gid_t,
) -> Result<TcpStream, HttpClientError> {
    let eyeball_config = EyeBallConfig::new(timeout.inner(), None);
    let happy_eyeballs = HappyEyeballs::new(addrs, eyeball_config);
    tcp_stream_with_owner(happy_eyeballs, uid, gid).await
}

#[cfg(feature = "http3")]
pub(crate) async fn udp_stream(
    addr: &std::net::SocketAddr,
) -> Result<ConnectedUdpSocket, HttpClientError> {
    let local_addr = match addr {
        std::net::SocketAddr::V4(_) => "0.0.0.0:0",
        std::net::SocketAddr::V6(_) => "[::]:0",
    };
    let sock = UdpSocket::bind(local_addr)
        .await
        .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
    sock.connect(addr)
        .await
        .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))
}

#[cfg(not(feature = "__tls"))]
mod no_tls {
    use core::future::Future;
    use core::pin::Pin;
    use std::time::Instant;

    use ylong_http::request::uri::Uri;

    use super::{eyeballs_connect, Connector, HttpConnector};
    use crate::async_impl::connector::dns_query;
    use crate::async_impl::connector::stream::HttpStream;
    use crate::runtime::TcpStream;
    use crate::util::config::HttpVersion;
    use crate::util::interceptor::ConnProtocol;
    use crate::{ConnData, ConnDetail, HttpClientError, TimeGroup};

    impl Connector for HttpConnector {
        type Stream = HttpStream<TcpStream>;
        type Future =
            Pin<Box<dyn Future<Output = Result<Self::Stream, HttpClientError>> + Sync + Send>>;

        fn connect(&self, uri: &Uri, _http_version: HttpVersion) -> Self::Future {
            // Checks if this uri need be proxied.
            let mut is_proxy = false;
            let mut addr = uri.authority().unwrap().to_string();
            if let Some(proxy) = self.config.proxies.match_proxy(uri) {
                addr = proxy.via_proxy(uri).authority().unwrap().to_string();
                is_proxy = true;
            }

            let resolver = self.resolver.clone();
            let timeout = self.config.timeout.clone();
            Box::pin(async move {
                let mut time_group = TimeGroup::default();
                time_group.set_dns_start(Instant::now());
                let socket_addrs = dns_query(resolver, addr.as_str()).await?;
                time_group.set_dns_end(Instant::now());
                time_group.set_tcp_start(Instant::now());
                let stream = eyeballs_connect(socket_addrs, timeout).await?;
                time_group.set_tcp_end(Instant::now());
                let local = stream
                    .local_addr()
                    .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
                let peer = stream
                    .peer_addr()
                    .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
                let detail = ConnDetail {
                    protocol: ConnProtocol::Tcp,
                    local,
                    peer,
                    addr,
                };

                let data = ConnData::builder()
                    .time_group(time_group)
                    .proxy(is_proxy)
                    .build(detail);
                Ok(HttpStream::new(stream, data))
            })
        }
    }
}

#[cfg(feature = "__tls")]
mod tls {
    #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
    use super::eyeballs_connect_with_owner;
    use super::{eyeballs_connect, Connector, HttpConnector};
    use crate::async_impl::connector::dns_query;
    use crate::async_impl::connector::stream::HttpStream;
    use crate::async_impl::mix::MixStream;
    #[cfg(feature = "http3")]
    use crate::async_impl::quic::QuicConn;
    use crate::async_impl::ssl_stream::AsyncSslStream;
    use crate::runtime::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt, TcpStream};
    use crate::util::c_openssl::adapter::TlsConfigBuilder;
    use crate::util::config::{Certificate, HttpVersion, ProxyTlsConfig};
    #[cfg(feature = "http2")]
    use crate::util::information::NegotiateInfo;
    use crate::util::interceptor::ConnProtocol;
    use crate::{ConnData, ConnDetail, HttpClientError, TimeGroup, TlsConfig};
    use core::future::Future;
    use core::pin::Pin;
    use std::error;
    use std::fmt::{Debug, Display, Formatter};
    use std::io::{Error, ErrorKind, Write};
    use std::time::Instant;
    use ylong_http::request::uri::{Scheme, Uri};

    impl Connector for HttpConnector {
        type Stream = HttpStream<MixStream>;
        type Future =
            Pin<Box<dyn Future<Output = Result<Self::Stream, HttpClientError>> + Sync + Send>>;

        fn connect(&self, uri: &Uri, _http_version: HttpVersion) -> Self::Future {
            // Make sure all parts of uri is accurate.
            let mut addr = uri.authority().unwrap().to_string();
            let mut auth = None;
            let mut is_proxy = false;
            let mut proxy_tls_config: Option<ProxyTlsConfig> = None;

            if let Some(proxy) = self.config.proxies.match_proxy(uri) {
                addr = proxy.via_proxy(uri).authority().unwrap().to_string();
                auth = proxy
                    .intercept
                    .proxy_info()
                    .basic_auth
                    .as_ref()
                    .and_then(|v| v.to_string().ok());
                is_proxy = true;
                if proxy.is_https_proxy() {
                    proxy_tls_config = Some(proxy.tls_config.clone());
                }
            }
            #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
            let fchown = self.config.fchown.clone();
            let resolver = self.resolver.clone();
            let timeout = self.config.timeout.clone();
            match *uri.scheme().unwrap() {
                Scheme::HTTP => Box::pin(async move {
                    let mut time_group = TimeGroup::default();
                    time_group.set_dns_start(Instant::now());
                    let socket_addrs = dns_query(resolver, addr.as_str()).await?;
                    time_group.set_dns_end(Instant::now());
                    time_group.set_tcp_start(Instant::now());
                    #[cfg(not(all(
                        target_os = "linux",
                        feature = "ylong_base",
                        feature = "__tls"
                    )))]
                    let stream = eyeballs_connect(socket_addrs, timeout).await?;
                    #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls"))]
                    let stream = if let Some(fchown) = fchown {
                        eyeballs_connect_with_owner(socket_addrs, timeout, fchown.uid, fchown.gid)
                            .await?
                    } else {
                        eyeballs_connect(socket_addrs, timeout).await?
                    };

                    time_group.set_tcp_end(Instant::now());

                    let local = stream.local_addr().map_err(|e| {
                        HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
                    })?;
                    let peer = stream.peer_addr().map_err(|e| {
                        HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
                    })?;
                    let detail = ConnDetail {
                        protocol: ConnProtocol::Tcp,
                        local,
                        peer,
                        addr,
                    };
                    let data = ConnData::builder()
                        .time_group(time_group)
                        .proxy(is_proxy)
                        .build(detail);

                    Ok(HttpStream::new(MixStream::Http(stream), data))
                }),
                Scheme::HTTPS => {
                    let host = uri.host().unwrap().to_string();
                    let port = uri.port().unwrap().as_u16().unwrap();
                    let config = self.config.tls.clone();
                    #[cfg(feature = "http3")]
                    if _http_version == HttpVersion::Http3 {
                        return Box::pin(async move {
                            let mut time_group = TimeGroup::default();
                            time_group.set_dns_start(Instant::now());
                            let addr_fut = resolver.resolve(&addr);
                            let addrs = addr_fut.await.map_err(|e| {
                                HttpClientError::from_dns_error(
                                    crate::ErrorKind::Connect,
                                    Error::new(ErrorKind::Interrupted, e),
                                )
                            })?;
                            time_group.set_dns_end(Instant::now());
                            time_group.set_quic_start(Instant::now());
                            let mut last_e = None;
                            for addr_it in addrs {
                                let udp_socket = match super::udp_stream(&addr_it).await {
                                    Ok(socket) => socket,
                                    Err(e) => {
                                        last_e = Some(e);
                                        continue;
                                    }
                                };
                                let local = udp_socket.local_addr().map_err(|e| {
                                    HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
                                })?;
                                let peer = udp_socket.peer_addr().map_err(|e| {
                                    HttpClientError::from_io_error(crate::ErrorKind::Connect, e)
                                })?;
                                let detail = ConnDetail {
                                    protocol: ConnProtocol::Quic,
                                    local,
                                    peer,
                                    addr: addr.clone(),
                                };

                                let mut data = ConnData::builder()
                                    .time_group(time_group.clone())
                                    .proxy(is_proxy)
                                    .build(detail);

                                let mut stream =
                                    HttpStream::new(MixStream::Udp(udp_socket), data.clone());
                                let Ok(quic_conn) =
                                    QuicConn::connect(&mut stream, &config, &host).await
                                else {
                                    continue;
                                };
                                stream.set_quic_conn(quic_conn);
                                data.time_group_mut().set_quic_end(Instant::now());
                                stream.set_conn_data(data);
                                return Ok(stream);
                            }

                            Err(last_e.unwrap_or(HttpClientError::from_str(
                                crate::ErrorKind::Connect,
                                "connect failed",
                            )))
                        });
                    }
                    Box::pin(async move {
                        let mut time_group = TimeGroup::default();
                        time_group.set_dns_start(Instant::now());
                        let socket_addrs = dns_query(resolver, addr.as_str()).await?;
                        time_group.set_dns_end(Instant::now());
                        time_group.set_tcp_start(Instant::now());
                        #[cfg(not(all(
                            target_os = "linux",
                            feature = "ylong_base",
                            feature = "__tls"
                        )))]
                        let stream = eyeballs_connect(socket_addrs, timeout).await?;
                        #[cfg(all(target_os = "linux", feature = "ylong_base", feature = "__tls",))]
                        let stream = if let Some(fchown) = fchown {
                            eyeballs_connect_with_owner(
                                socket_addrs,
                                timeout,
                                fchown.uid,
                                fchown.gid,
                            )
                            .await?
                        } else {
                            eyeballs_connect(socket_addrs, timeout).await?
                        };

                        time_group.set_tcp_end(Instant::now());

                        https_connect(
                            config,
                            addr,
                            stream,
                            is_proxy,
                            (auth, host, port),
                            time_group,
                            proxy_tls_config,
                        )
                        .await
                    })
                }
            }
        }
    }

    async fn https_connect(
        config: TlsConfig,
        addr: String,
        tcp_stream: TcpStream,
        is_proxy: bool,
        (auth, host, port): (Option<String>, String, u16),
        mut time_group: TimeGroup,
        proxy_tls_config: Option<ProxyTlsConfig>,
    ) -> Result<HttpStream<MixStream>, HttpClientError> {
        let tcp = tcp_stream;
        let local = tcp
            .local_addr()
            .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;
        let peer = tcp
            .peer_addr()
            .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;

        if is_proxy {
            if let Some(proxy_tls) = proxy_tls_config {
                let proxy_config = proxy_tls_config_to_tls_config(&config, &proxy_tls)?;
                let proxy_addr = &addr;

                let pinned_key = proxy_config.pinning_host_match(proxy_addr);
                let mut proxy_ssl_stream = proxy_config
                    .ssl_new(proxy_addr)
                    .and_then(|ssl| AsyncSslStream::new(ssl.into_inner(), tcp, pinned_key))
                    .map_err(|e| {
                        HttpClientError::from_tls_error(
                            crate::ErrorKind::Connect,
                            Error::new(ErrorKind::Other, format!("[proxy] {}", e)),
                        )
                    })?;

                time_group.set_tls_start(Instant::now());
                Pin::new(&mut proxy_ssl_stream)
                    .connect()
                    .await
                    .map_err(|e| {
                        HttpClientError::from_tls_error(
                            crate::ErrorKind::Connect,
                            Error::new(ErrorKind::Other, format!("[proxy] {}", e)),
                        )
                    })?;
                time_group.set_tls_end(Instant::now());

                proxy_ssl_stream = tunnel_over_proxy_tls(proxy_ssl_stream, &host, port, auth)
                    .await
                    .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;

                let pinned_key = config.pinning_host_match(addr.as_str());
                let mut target_ssl_stream = config
                    .ssl_new(&host)
                    .and_then(|ssl| {
                        AsyncSslStream::new(ssl.into_inner(), proxy_ssl_stream, pinned_key)
                    })
                    .map_err(|e| {
                        HttpClientError::from_tls_error(
                            crate::ErrorKind::Connect,
                            Error::new(ErrorKind::Other, e),
                        )
                    })?;

                time_group.set_tls_start(Instant::now());
                Pin::new(&mut target_ssl_stream)
                    .connect()
                    .await
                    .map_err(|e| {
                        HttpClientError::from_tls_error(
                            crate::ErrorKind::Connect,
                            Error::new(ErrorKind::Other, e),
                        )
                    })?;
                time_group.set_tls_end(Instant::now());

                #[cfg(feature = "http2")]
                let alpn = target_ssl_stream.negotiated_alpn_protocol().map(Vec::from);
                let detail = ConnDetail {
                    protocol: ConnProtocol::Tcp,
                    local,
                    peer,
                    addr,
                };

                #[cfg(feature = "http2")]
                let data = ConnData::builder()
                    .time_group(time_group)
                    .proxy(is_proxy)
                    .negotiate(NegotiateInfo::from_alpn(alpn))
                    .build(detail);

                #[cfg(not(feature = "http2"))]
                let data = ConnData::builder()
                    .time_group(time_group)
                    .proxy(is_proxy)
                    .build(detail);

                return Ok(HttpStream::new(
                    MixStream::HttpsProxy(target_ssl_stream),
                    data,
                ));
            }

            let mut tcp = tcp;
            tcp = tunnel(tcp, &host, port, auth)
                .await
                .map_err(|e| HttpClientError::from_io_error(crate::ErrorKind::Connect, e))?;

            let pinned_key = config.pinning_host_match(addr.as_str());
            let mut stream = config
                .ssl_new(&host)
                .and_then(|ssl| AsyncSslStream::new(ssl.into_inner(), tcp, pinned_key))
                .map_err(|e| {
                    HttpClientError::from_tls_error(
                        crate::ErrorKind::Connect,
                        Error::new(ErrorKind::Other, e),
                    )
                })?;

            time_group.set_tls_start(Instant::now());
            Pin::new(&mut stream).connect().await.map_err(|e| {
                HttpClientError::from_tls_error(
                    crate::ErrorKind::Connect,
                    Error::new(ErrorKind::Other, e),
                )
            })?;
            time_group.set_tls_end(Instant::now());

            #[cfg(feature = "http2")]
            let alpn = stream.negotiated_alpn_protocol().map(Vec::from);
            let detail = ConnDetail {
                protocol: ConnProtocol::Tcp,
                local,
                peer,
                addr,
            };

            #[cfg(feature = "http2")]
            let data = ConnData::builder()
                .time_group(time_group)
                .proxy(is_proxy)
                .negotiate(NegotiateInfo::from_alpn(alpn))
                .build(detail);

            #[cfg(not(feature = "http2"))]
            let data = ConnData::builder()
                .time_group(time_group)
                .proxy(is_proxy)
                .build(detail);

            return Ok(HttpStream::new(MixStream::Https(stream), data));
        }

        let pinned_key = config.pinning_host_match(addr.as_str());
        let mut stream = config
            .ssl_new(&host)
            .and_then(|ssl| AsyncSslStream::new(ssl.into_inner(), tcp, pinned_key))
            .map_err(|e| {
                HttpClientError::from_tls_error(
                    crate::ErrorKind::Connect,
                    Error::new(ErrorKind::Other, e),
                )
            })?;

        time_group.set_tls_start(Instant::now());
        Pin::new(&mut stream).connect().await.map_err(|e| {
            HttpClientError::from_tls_error(
                crate::ErrorKind::Connect,
                Error::new(ErrorKind::Other, e),
            )
        })?;
        time_group.set_tls_end(Instant::now());

        #[cfg(feature = "http2")]
        let alpn = stream.negotiated_alpn_protocol().map(Vec::from);
        let detail = ConnDetail {
            protocol: ConnProtocol::Tcp,
            local,
            peer,
            addr,
        };

        #[cfg(feature = "http2")]
        let data = ConnData::builder()
            .time_group(time_group)
            .proxy(is_proxy)
            .negotiate(NegotiateInfo::from_alpn(alpn))
            .build(detail);

        #[cfg(not(feature = "http2"))]
        let data = ConnData::builder()
            .time_group(time_group)
            .proxy(is_proxy)
            .build(detail);

        Ok(HttpStream::new(MixStream::Https(stream), data))
    }

    fn proxy_tls_config_to_tls_config(
        _base_config: &TlsConfig,
        proxy_tls: &ProxyTlsConfig,
    ) -> Result<TlsConfig, HttpClientError> {
        let builder = TlsConfig::builder();
        proxy_tls
            .apply_to_builder(builder)
            .and_then(|b: TlsConfigBuilder| b.build())
    }

    async fn tunnel(
        mut conn: TcpStream,
        host: &str,
        port: u16,
        auth: Option<String>,
    ) -> Result<TcpStream, Error> {
        let mut req = Vec::new();

        write!(
            &mut req,
            "CONNECT {host}:{port} HTTP/1.1\r\nHost: {host}:{port}\r\n"
        )?;

        if let Some(value) = auth {
            write!(&mut req, "Proxy-Authorization: Basic {value}\r\n")?;
        }

        write!(&mut req, "\r\n")?;

        conn.write_all(&req).await?;

        let mut buf = [0; 8192];
        let mut pos = 0;

        loop {
            let n = conn.read(&mut buf[pos..]).await?;

            if n == 0 {
                return Err(other_io_error(CreateTunnelErr::Unsuccessful));
            }

            pos += n;
            let resp = &buf[..pos];
            if resp.starts_with(b"HTTP/1.1 200") || resp.starts_with(b"HTTP/1.0 200") {
                if resp.ends_with(b"\r\n\r\n") {
                    return Ok(conn);
                }
                if pos == buf.len() {
                    return Err(other_io_error(CreateTunnelErr::ProxyHeadersTooLong));
                }
            } else if resp.starts_with(b"HTTP/1.1 407") {
                return Err(other_io_error(CreateTunnelErr::ProxyAuthenticationRequired));
            } else {
                return Err(other_io_error(CreateTunnelErr::Unsuccessful));
            }
        }
    }

    async fn tunnel_over_proxy_tls<S>(
        mut conn: AsyncSslStream<S>,
        host: &str,
        port: u16,
        auth: Option<String>,
    ) -> Result<AsyncSslStream<S>, Error>
    where
        S: AsyncRead + AsyncWrite + Unpin,
    {
        let mut req = Vec::new();

        write!(
            &mut req,
            "CONNECT {host}:{port} HTTP/1.1\r\nHost: {host}:{port}\r\n"
        )?;

        if let Some(value) = auth {
            write!(&mut req, "Proxy-Authorization: Basic {value}\r\n")?;
        }

        write!(&mut req, "\r\n")?;

        Pin::new(&mut conn).write_all(&req).await?;

        let mut buf = [0; 8192];
        let mut pos = 0;

        loop {
            let n = Pin::new(&mut conn).read(&mut buf[pos..]).await?;

            if n == 0 {
                return Err(other_io_error(CreateTunnelErr::Unsuccessful));
            }

            pos += n;
            let resp = &buf[..pos];
            if resp.starts_with(b"HTTP/1.1 200") || resp.starts_with(b"HTTP/1.0 200") {
                if resp.ends_with(b"\r\n\r\n") {
                    return Ok(conn);
                }
                if pos == buf.len() {
                    return Err(other_io_error(CreateTunnelErr::ProxyHeadersTooLong));
                }
            } else if resp.starts_with(b"HTTP/1.1 407") {
                return Err(other_io_error(CreateTunnelErr::ProxyAuthenticationRequired));
            } else {
                return Err(other_io_error(CreateTunnelErr::Unsuccessful));
            }
        }
    }

    fn other_io_error(err: CreateTunnelErr) -> Error {
        Error::new(ErrorKind::Other, err)
    }

    enum CreateTunnelErr {
        ProxyHeadersTooLong,
        ProxyAuthenticationRequired,
        Unsuccessful,
    }

    impl Debug for CreateTunnelErr {
        fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
            match self {
                Self::ProxyHeadersTooLong => f.write_str("Proxy headers too long for tunnel"),
                Self::ProxyAuthenticationRequired => f.write_str("Proxy authentication required"),
                Self::Unsuccessful => f.write_str("Unsuccessful tunnel"),
            }
        }
    }

    impl Display for CreateTunnelErr {
        fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
            Debug::fmt(self, f)
        }
    }

    impl error::Error for CreateTunnelErr {}

    #[cfg(all(test, feature = "__tls"))]
    mod ut_tunnel_error_debug {
        use crate::async_impl::connector::tls::CreateTunnelErr;

        /// UT test cases for debug of`CreateTunnelErr`.
        ///
        /// # Brief
        /// 1. Checks `CreateTunnelErr` debug by calling `CreateTunnelErr::fmt`.
        /// 2. Checks if the result is as expected.
        #[test]
        fn ut_tunnel_error_debug_assert() {
            assert_eq!(
                format!("{:?}", CreateTunnelErr::ProxyHeadersTooLong),
                "Proxy headers too long for tunnel"
            );
            assert_eq!(
                format!("{:?}", CreateTunnelErr::ProxyAuthenticationRequired),
                "Proxy authentication required"
            );
            assert_eq!(
                format!("{:?}", CreateTunnelErr::Unsuccessful),
                "Unsuccessful tunnel"
            );
            assert_eq!(
                format!("{}", CreateTunnelErr::ProxyHeadersTooLong),
                "Proxy headers too long for tunnel"
            );
            assert_eq!(
                format!("{}", CreateTunnelErr::ProxyAuthenticationRequired),
                "Proxy authentication required"
            );
            assert_eq!(
                format!("{}", CreateTunnelErr::Unsuccessful),
                "Unsuccessful tunnel"
            );
        }
    }

    #[cfg(all(test, feature = "__tls", feature = "ylong_base"))]
    mod ut_create_tunnel_err_debug {
        use std::net::SocketAddr;
        use std::str::FromStr;

        use ylong_runtime::io::AsyncWriteExt;

        use crate::async_impl::connector::tcp_stream;
        use crate::async_impl::connector::tls::{other_io_error, tunnel, CreateTunnelErr};
        use crate::async_impl::dns::{EyeBallConfig, HappyEyeballs};
        use crate::start_tcp_server;
        use crate::util::test_utils::{format_header_str, TcpHandle};

        /// UT test cases for `tunnel`.
        ///
        /// # Brief
        /// 1. Creates a `tcp stream` by calling `tcp_stream`.
        /// 2. Sends a `Request` by `tunnel`.
        /// 3. Checks if the result is as expected.
        #[test]
        fn ut_ssl_tunnel_error() {
            let mut handles = vec![];
            start_tcp_server!(
               Handles: handles,
               EndWith: "\r\n\r\n",
               Shutdown: std::net::Shutdown::Both,
            );
            let handle = handles.pop().expect("No more handles !");

            let eyeballs = HappyEyeballs::new(
                vec![SocketAddr::from_str(handle.addr.as_str()).unwrap()],
                EyeBallConfig::new(None, None),
            );

            let handle = ylong_runtime::spawn(async move {
                let tcp = tcp_stream(eyeballs).await.unwrap();
                let res = tunnel(
                    tcp,
                    "ylong_http.com",
                    443,
                    Some(String::from("base64 bytes")),
                )
                .await;
                assert_eq!(
                    format!("{:?}", res.err()),
                    format!("{:?}", Some(other_io_error(CreateTunnelErr::Unsuccessful)))
                );
                handle
                    .server_shutdown
                    .recv()
                    .expect("server send order failed !");
            });
            ylong_runtime::block_on(handle).unwrap();

            start_tcp_server!(
               Handles: handles,
               EndWith: "\r\n\r\n",
               Response: {
                   Status: 407,
                   Version: "HTTP/1.1",
                   Header: "Content-Length", "11",
                   Body: "METHOD GET!",
               },
               Shutdown: std::net::Shutdown::Both,
            );
            let handle = handles.pop().expect("No more handles !");

            let eyeballs = HappyEyeballs::new(
                vec![SocketAddr::from_str(handle.addr.as_str()).unwrap()],
                EyeBallConfig::new(None, None),
            );
            let handle = ylong_runtime::spawn(async move {
                let tcp = tcp_stream(eyeballs).await.unwrap();
                let res = tunnel(
                    tcp,
                    "ylong_http.com",
                    443,
                    Some(String::from("base64 bytes")),
                )
                .await;
                assert_eq!(
                    format!("{:?}", res.err()),
                    format!(
                        "{:?}",
                        Some(other_io_error(CreateTunnelErr::ProxyAuthenticationRequired))
                    )
                );
                handle
                    .server_shutdown
                    .recv()
                    .expect("server send order failed !");
            });
            ylong_runtime::block_on(handle).unwrap();

            start_tcp_server!(
               Handles: handles,
               EndWith: "\r\n\r\n",
               Response: {
                   Status: 402,
                   Version: "HTTP/1.1",
                   Header: "Content-Length", "11",
                   Body: "METHOD GET!",
               },
               Shutdown: std::net::Shutdown::Both,
            );
            let handle = handles.pop().expect("No more handles !");

            let eyeballs = HappyEyeballs::new(
                vec![SocketAddr::from_str(handle.addr.as_str()).unwrap()],
                EyeBallConfig::new(None, None),
            );
            let handle = ylong_runtime::spawn(async move {
                let tcp = tcp_stream(eyeballs).await.unwrap();
                let res = tunnel(
                    tcp,
                    "ylong_http.com",
                    443,
                    Some(String::from("base64 bytes")),
                )
                .await;
                assert_eq!(
                    format!("{:?}", res.err()),
                    format!("{:?}", Some(other_io_error(CreateTunnelErr::Unsuccessful)))
                );
                handle
                    .server_shutdown
                    .recv()
                    .expect("server send order failed !");
            });
            ylong_runtime::block_on(handle).unwrap();
        }

        /// UT test cases for `tunnel`.
        ///
        /// # Brief
        /// 1. Creates a `tcp stream` by calling `tcp_stream`.
        /// 2. Sends a `Request` by `tunnel`.
        /// 3. Checks if the result is as expected.
        #[test]
        fn ut_ssl_tunnel_connect() {
            let mut handles = vec![];

            start_tcp_server!(
               Handles: handles,
               EndWith: "\r\n\r\n",
                Response: {
                   Status: 200,
                   Version: "HTTP/1.1",
                   Body: "",
               },
               Shutdown: std::net::Shutdown::Both,
            );
            let handle = handles.pop().expect("No more handles !");

            let eyeballs = HappyEyeballs::new(
                vec![SocketAddr::from_str(handle.addr.as_str()).unwrap()],
                EyeBallConfig::new(None, None),
            );
            let handle = ylong_runtime::spawn(async move {
                let tcp = tcp_stream(eyeballs).await.unwrap();
                let res = tunnel(
                    tcp,
                    "ylong_http.com",
                    443,
                    Some(String::from("base64 bytes")),
                )
                .await;
                assert!(res.is_ok());
                handle
                    .server_shutdown
                    .recv()
                    .expect("server send order failed !");
            });
            ylong_runtime::block_on(handle).unwrap();
        }

        /// UT test cases for response beyond size of `tunnel`.
        ///
        /// # Brief
        /// 1. Creates a `tcp stream` by calling `tcp_stream`.
        /// 2. Sends a `Request` by `tunnel`.
        /// 3. Checks if the result is as expected.
        #[test]
        fn ut_ssl_tunnel_resp_beyond_size() {
            let mut handles = vec![];

            let buf = vec![b'b'; 8192];
            let body = String::from_utf8(buf).unwrap();

            start_tcp_server!(
               Handles: handles,
               EndWith: "\r\n\r\n",
                Response: {
                   Status: 200,
                   Version: "HTTP/1.1",
                   Header: "Content-Length", "11",
                   Body: body.as_str(),
               },
            );
            let handle = handles.pop().expect("No more handles !");

            let eyeballs = HappyEyeballs::new(
                vec![SocketAddr::from_str(handle.addr.as_str()).unwrap()],
                EyeBallConfig::new(None, None),
            );
            let handle = ylong_runtime::spawn(async move {
                let tcp = tcp_stream(eyeballs).await.unwrap();
                let res = tunnel(
                    tcp,
                    "ylong_http.com",
                    443,
                    Some(String::from("base64 bytes")),
                )
                .await;
                assert_eq!(
                    format!("{:?}", res.err()),
                    format!(
                        "{:?}",
                        Some(other_io_error(CreateTunnelErr::ProxyHeadersTooLong))
                    )
                );
                handle
                    .server_shutdown
                    .recv()
                    .expect("server send order failed !");
            });
            ylong_runtime::block_on(handle).unwrap();
        }
    }
}
